### ISSUE TITLE
Calling json() more than once raises KeyError

### ISSUE THREAD

**Issue by nemesisdesign** [ninuxorg/netdiff#30]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netdiff/parsers/base.py", line 152, in json
    **kwargs)
  File "netdiff/utils.py", line 138, in _netjson_networkgraph
    ('weight', link[2].pop('weight'))
KeyError: 'weight'
```

**Comment by nemesisdesign** [comment]
False alarm
